### ISSUE TITLE
Stocksnap now requires a `User-Agent` header

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-catalog#759]
## Description

After applying the fix described in #758 locally, I tried running the DAG but I was met with the following error:

```python
[2022-10-01, 00:10:50 UTC] {factory_utils.py:135} INFO - Beginning ingestion
[2022-10-01, 00:10:50 UTC] {provider_data_ingester.py:151} INFO - Begin ingestion for StockSnapDataIngester
[2022-10-01, 00:10:50 UTC] {requester.py:69} WARNING - Unable to request URL: https://stocksnap.io/api/load-photos/date/desc/1.  Status code: 403
[2022-10-01, 00:10:50 UTC] {requester.py:115} WARNING - Bad response_json:  None
[2022-10-01, 00:10:50 UTC] {requester.py:116} WARNING - Retrying:
_get_response_json(
    https://stocksnap.io/api/load-photos/date/desc/1,
    {},
    retries=2)
[2022-10-01, 00:10:51 UTC] {requester.py:69} WARNING - Unable to request URL: https://stocksnap.io/api/load-photos/date/desc/1.  Status code: 403
[2022-10-01, 00:10:51 UTC] {requester.py:115} WARNING - Bad response_json:  None
[2022-10-01, 00:10:51 UTC] {requester.py:116} WARNING - Retrying:
_get_response_json(
    https://stocksnap.io/api/load-photos/date/desc/1,
    {},
    retries=1)
[2022-10-01, 00:10:52 UTC] {requester.py:69} WARNING - Unable to request URL: https://stocksnap.io/api/load-photos/date/desc/1.  Status code: 403
[2022-10-01, 00:10:52 UTC] {requester.py:115} WARNING - Bad response_json:  None
[2022-10-01, 00:10:52 UTC] {requester.py:116} WARNING - Retrying:
_get_response_json(
    https://stocksnap.io/api/load-photos/date/desc/1,
    {},
    retries=0)
[2022-10-01, 00:10:53 UTC] {requester.py:69} WARNING - Unable to request URL: https://stocksnap.io/api/load-photos/date/desc/1.  Status code: 403
[2022-10-01, 00:10:53 UTC] {requester.py:115} WARNING - Bad response_json:  None
[2022-10-01, 00:10:53 UTC] {requester.py:116} WARNING - Retrying:
_get_response_json(
    https://stocksnap.io/api/load-photos/date/desc/1,
    {},
    retries=-1)
[2022-10-01, 00:10:53 UTC] {requester.py:101} ERROR - No retries remaining.  Failure.
[2022-10-01, 00:10:53 UTC] {provider_data_ingester.py:396} INFO - Committed 0 records
[2022-10-01, 00:10:53 UTC] {taskinstance.py:1851} ERROR - Task failed with exception
providers.provider_api_scripts.provider_data_ingester.IngestionError: Retries exceeded
query_params: {}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/openverse_catalog/dags/providers/factory_utils.py", line 140, in pull_media_wrapper
    data = run_func(*args)
  File "/usr/local/airflow/openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py", line 194, in ingest_records
    raise error from ingestion_error
  File "/usr/local/airflow/openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py", line 161, in ingest_records
    batch, should_continue = self.get_batch(query_params)
  File "/usr/local/airflow/openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py", line 295, in get_batch
    response_json = self.get_response_json(query_params)
  File "/usr/local/airflow/openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py", line 314, in get_response_json
    return self.delayed_requester.get_response_json(
  File "/usr/local/airflow/openverse_catalog/dags/common/requester.py", line 123, in get_response_json
    response_json = self.get_response_json(
  File "/usr/local/airflow/openverse_catalog/dags/common/requester.py", line 123, in get_response_json
    response_json = self.get_response_json(
  File "/usr/local/airflow/openverse_catalog/dags/common/requester.py", line 123, in get_response_json
    response_json = self.get_response_json(
  [Previous line repeated 1 more time]
  File "/usr/local/airflow/openverse_catalog/dags/common/requester.py", line 102, in get_response_json
    raise RetriesExceeded("Retries exceeded")
common.requester.RetriesExceeded: Retries exceeded
```

I added a faux `User-Agent` to the headers and was able to get past that step, but then also got these logs:

```[2022-10-01, 00:17:47 UTC] {provider_data_ingester.py:151} INFO - Begin ingestion for StockSnapDataIngester
[2022-10-01, 00:17:48 UTC] {requester.py:69} WARNING - Unable to request URL: https://cdn.stocksnap.io/img-thumbs/960w/AMEYDHBGJF.jpg.  Status code: 403
[2022-10-01, 00:17:49 UTC] {requester.py:69} WARNING - Unable to request URL: https://cdn.stocksnap.io/img-thumbs/960w/XGMAQNG7PY.jpg.  Status code: 403
[2022-10-01, 00:17:50 UTC] {requester.py:69} WARNING - Unable to request URL: https://cdn.stocksnap.io/img-thumbs/960w/KGCLUBUAEW.jpg.  Status code: 403
[2022-10-01, 00:17:51 UTC] {requester.py:69} WARNING - Unable to request URL: https://cdn.stocksnap.io/img-thumbs/960w/G4YYZSAXAT.jpg.  Status code: 403
[2022-10-01, 00:17:52 UTC] {requester.py:69} WARNING - Unable to request URL: https://cdn.stocksnap.io/img-thumbs/960w/REBSHVJHFH.jpg.  Status code: 403
[2022-10-01, 00:17:53 UTC] {requester.py:69} WARNING - Unable to request URL: https://cdn.stocksnap.io/img-thumbs/960w/THGALOFGEU.jpg.  Status code: 403
[2022-10-01, 00:17:54 UTC] {requester.py:69} WARNING - Unable to request URL: https://cdn.stocksnap.io/img-thumbs/960w/L98SVEZOVY.jpg.  Status code: 403
[2022-10-01, 00:17:55 UTC] {requester.py:69} WARNING - Unable to request URL: https://cdn.stocksnap.io/img-thumbs/960w/48WQRY7ULS.jpg.  Status code: 403
[2022-10-01, 00:17:56 UTC] {requester.py:69} WARNING - Unable to request URL: https://cdn.stocksnap.io/img-thumbs/960w/P3VSWDGHSQ.jpg.  Status code: 403
[2022-10-01, 00:17:57 UTC] {requester.py:69} WARNING - Unable to request URL: https://cdn.stocksnap.io/img-thumbs/960w/8BQCLWJLDK.jpg.  Status code: 403
[2022-10-01, 00:17:58 UTC] {requester.py:69} WARNING - Unable to request URL: https://cdn.stocksnap.io/img-thumbs/960w/THV0XGK4LP.jpg.  Status code: 403
[2022-10-01, 00:17:59 UTC] {requester.py:69} WARNING - Unable to request URL: https://cdn.stocksnap.io/img-thumbs/960w/MF8LSXR049.jpg.  Status code: 403
[2022-10-01, 00:18:00 UTC] {requester.py:69} WARNING - Unable to request URL: https://cdn.stocksnap.io/img-thumbs/960w/9KUQONMKX7.jpg.  Status code: 403
[2022-10-01, 00:18:01 UTC] {requester.py:69} WARNING - Unable to request URL: https://cdn.stocksnap.io/img-thumbs/960w/IJAX71RJBA.jpg.  Status code: 403
[2022-10-01, 00:18:02 UTC] {requester.py:69} WARNING - Unable to request URL: https://cdn.stocksnap.io/img-thumbs/960w/S9DODB5OXH.jpg.  Status code: 403
...
```

I believe that this is the result of the request in `_get_filesize`:

https://github.com/WordPress/openverse-catalog/blob/d828d257adc70121d0b2d8b926e3d625f700651c/openverse_catalog/dags/providers/provider_api_scripts/stocksnap.py#L157

_Note that this relates to #631, perhaps we should pass the `ProviderDataIngester::headers` attribute into the `DelayedRequester` at initialization time so all requests made within a class's `DelayedRequester` can use the default headers?_

## Reproduction

1. Apply the patch described in #758
2. Run the Stocksnap DAG
3. Add a `User-Agent` to the headers dict [here](https://github.com/WordPress/openverse-catalog/blob/d828d257adc70121d0b2d8b926e3d625f700651c/openverse_catalog/dags/providers/provider_api_scripts/stocksnap.py#L39)
4. Run the DAG again

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by AetherUnbound** [comment]
See also:

```python
[ins] In [1]: import requests

[ins] In [2]: r = requests.get("https://stocksnap.io/api/load-photos/date/desc/1")

[ins] In [3]: r
Out[3]: <Response [403]>

[ins] In [4]: r = requests.get("https://stocksnap.io/api/load-photos/date/desc/1", headers={"User-Agent": "madison-test-
         ...: bot"})

[ins] In [5]: r
Out[5]: <Response [200]>
```

**Comment by AetherUnbound** [comment]
Some example code for how to approach this can be found in the Wikimedia script:

https://github.com/WordPress/openverse-catalog/blob/18decf9b70f409bc83809d14b7be3b65cb91d409/openverse_catalog/dags/providers/provider_api_scripts/wikimedia_commons.py#L50
